fuel_types = ['plug_in_hybrid_petrol', 'diesel', 'petrol', 'lpg', 'hybrid_petrol','hybrid_diesel', 'electric', 'cng', 'plug_in_hybrid_diesel','other','hydrogen']
gearbox_types = ['automatic', 'manual', 'semi_automatic']
interior_types = ['fabric', 'leather_fabric', 'leather', 'alcantara', 'velours', 'other']
exterior_colors = ['black', 'white', 'blue','silver','purple','grey','red','light_blue', 'other','beige','brown','green','yellow','gold','chrome','burgundy','orange','lemon','pink']
interior_colors = ['black', 'two_colors', 'grey', 'beige', 'brown', 'other', 'white', 'red']
number_plate_endings = ['odd', 'unknown', 'even', 'without', 'historic']
drive_types = ['FWD', '4WD', 'RWD', 'AWD']
body_types =['hatchback','sedan','SUV','Pick-Up','van','station wagon','coupe','Hochdach-Kombi']
lat = 37.983810
longitude = 23.727539