name: Deploy Streamlit App For Car Estimation

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT }}

    - name: Set Up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Build and Push Docker Image
      run: |
        gcloud auth configure-docker
        gcloud builds submit --tag europe-west1-docker.pkg.dev/car-scraping-450821/docker-repo/streamlit-app:latest app/

    - name: Set default region for Cloud Run
      run: |
        gcloud config set run/region europe-west1

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy streamlit-app \
          --image=europe-west1-docker.pkg.dev/car-scraping-450821/docker-repo/streamlit-app:latest \
          --platform=managed \
          --region=europe-west1 \
          --service-account=streamlit-service-account@car-scraping-450821.iam.gserviceaccount.com \
          --allow-unauthenticated
